services:
  emage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emage-app
    ports:
      - "3000:80"
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=emage"
      - "description=Client-side image manipulation tool"
